import java.util.Scanner;
public class Atividade_02 {
    public static void main(String[] args) {
        Scanner ler = new Scanner(System.in);

        System.out.println("Digite um nome: ");
        String name = ler.next();

        System.out.println("Digite uma senha: ");
        String senha = ler.next();
        int tamSenha = senha.length();

        if(tamSenha >= 8){
            System.out.print("Sua senha está correta.");
        }
        else{
            System.out.print("Sua senha tem menos de 8 caracteres");
        }
    }
}
